### ISSUE TITLE
Add jenkins view for ui jobs

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/ci-management#407]
Not sure where to put this, but it would be nice if jenkins.edgexfoundry.org had a view category for all of the `edgex-ui-*` jobs (i.e. https://jenkins.edgexfoundry.org/view/Merge-Jobs/job/edgex-ui-go-master-merge-go/search/?q=edgex-ui&Jenkins-Crumb=c86df3190b6c686ae420ee0de9090c8f)
as currently I have to manually search for them every time I need to see one

**Comment by dweomer** [comment]
@anonymouse64 I believe that @tmpowers PR, https://github.com/edgexfoundry/ci-management/pull/406/files#diff-90cf5761f43d02aff48b25e448f522d9R3, has that as a side-effect

**Comment by anonymouse64** [comment]
Nice, yes that looks like it would do the trick

**Comment by jamesrgregg** [comment]
Fixed in #406

**Comment by anonymouse64** [comment]
@jamesrgregg please do not close issues until the issue is actually merged, i.e. the linked PR may eventually resolve the issue but it is not yet resolved because that PR hasn't been merged.

**Comment by jamesrgregg** [comment]
@anonymouse64 it was just an attempt to do some house cleaning ahead of the release tomorrow since those PRs will be processed then.  I have reopened this as requested.
